### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by Stetchy** [Stetchy/qlite-web#3]
**To Do**

- [ ]  Log in/register page
- [ ]  Load show page
- [X]  Show list component
- [ ]  Settings page
- [ ]  Individual settings component
- [ ]  Admin dashboard
- [ ]  Show page
- [ ]  Cue list component
- [ ]  QBox status component
- [X]  QBox select component
- [ ]  QBox type select component
- [X]  Endpoints
